### ISSUE TITLE
BUG: Opening Evaluation.evaluate tab triggers error in UI

### ISSUE THREAD

**Issue by nthomsencph** [wandb/weave#1614]
I keep getting this error when I select an Evaluation (Evaluation.evaluate) - Happens most times, not every time.

<img width="1850" alt="image" src="https://github.com/wandb/weave/assets/62802289/20884e96-d8ea-46d5-bdcf-4030dd48613a">

Happens here:
https://wandb.ai/cbs-nlp/llama-7b-chat_center_embed_tn1_ce-lvl1_n5_tn0_i1/weave/calls?filter=%7B%22frozen%22%3Atrue%2C%22opVersionRefs%22%3A%5B%22weave%3A%2F%2F%2Fcbs-nlp%2Fllama-7b-chat_center_embed_tn1_ce-lvl1_n5_tn0_i1%2Fop%2FEvaluation.evaluate%3A*%22%5D%7D&peekPath=%2Fcbs-nlp%2Fllama-7b-chat_center_embed_tn1_ce-lvl1_n5_tn0_i1%2Fcalls%2F75ac49c6-64c3-4a79-8ed7-a649c6b22be9

Stacktrace (Chrome)
<img width="931" alt="image" src="https://github.com/wandb/weave/assets/62802289/d5125e6f-45e5-4790-ae2a-4ecee638e86e">

**Comment by jwlee64** [comment]
Hi @nthomsencph, sorry about error and thank you for sending in a bug report and a project with that repro, I will file an internal ticket and someone will hop on that as soon as possible.
https://wandb.atlassian.net/browse/WB-18743

**Comment by jamie-rasmussen** [comment]
Thank you again for the detailed error report. This error is occurring because of the '/' character being used in object names, which is causing problems in parts of our code that use that as a delimiter. If possible I would recommend avoiding any special characters like that. Letters, numbers, dashes, and underscores should continue to be safe. We do intend to introduce more strict limitations on names.

We've deployed a fix that should prevent the URL you linked from crashing in that way, but I believe you are likely to encounter other problems with objects named like this until we can do a more comprehensive fix.

**Comment by tssweeney** [comment]
Confirming that the initial fix from Jamie does allow the page to render, but these names are not handled properly in all cases. @nthomsencph we will be putting in place backend checks to stop such names in the future, so it is advised to change the names now if possible.

**Comment by nthomsencph** [comment]
Thanks for the clarification and swift action!
