### ISSUE TITLE
np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

### ISSUE THREAD

**Issue by farzad528** [wandb/weave#2098]
When running 
```
import weave
weave.init(f"{WANDB_PROJECT}")
```

I get the following error: AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

I tried upgrading weave and numpy but doesn't seem to work.

**Comment by gtarpenning** [comment]
Hey @farzad528 thanks for writing in. It looks like this may be caused by an out of date `wandb` package version as per [this  closed issue](https://github.com/wandb/wandb/issues/7810) in the wandb repo. This should be fixed in versions of `wandb` including and after [`0.17.2`](https://github.com/wandb/wandb/releases/tag/v0.17.2).

Let us know if upgrading your `wandb` package resolves the issue!

**Comment by gtarpenning** [comment]
@farzad528 Closing this issue as I believe it is resolved, if not I will gladly reopen.
